export const motorsCarCard = {
  CarInfo: [
    {
      id: 1,
      car: {
        photo: "src={camping}",
        name: "르벤투스S+",
        cost: "90,200,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "4인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 2,
      car: {
        photo: "//",
        name: "르벤투스680S",
        cost: "93,700,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "4인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 3,
      car: {
        photo: "//",
        name: "르벤투스680",
        cost: "93,700,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "5인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 4,
      car: {
        photo: "//",
        name: "르벤투스 차박S",
        cost: "66,100,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "4인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 5,
      car: {
        photo: "//",
        name: "포스650",
        cost: "85,300,000",
        type: "포터",
        license: "2종 보통",
        people: "6인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 6,
      car: {
        photo: "//",
        name: "포스560",
        cost: "93,700,000",
        type: "포터",
        license: "2종 보통",
        people: "6인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 7,
      car: {
        photo: "//",
        name: "올카",
        cost: "62,600,000",
        type: "포터",
        license: "2종 보통",
        people: "3인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 8,
      car: {
        photo: "//",
        name: "DS9eR+a",
        cost: "77,900,000",
        type: "봉고",
        license: "2종 보통",
        people: "6인",
        date: "22년 03월",
        company: "제일모빌",
        location: "수도권",
      },
    },

  ],
};
