name: CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: connect to server and deploy changes
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -e
            cd camper-client/
            git pull origin master
            rm -rf ./build
            rm -rf /var/www/dream-camper
            mkdir -p /var/www/dream-camper
            npm install --legacy-peer-deps
            npm run build
            cp -rf ./build/* /var/www/dream-camper
            pm2 restart dream-camper
