name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run SSH commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd camper-client/
          git pull origin master
          rm -rf ./build
          rm -rf /var/www/dream-camper
          mkdir /var/www/dream-camper
          npm i --legacy-peer-deps
          npm run build
          cp -rf ./build/* /var/www/dream-camper
          npm install -g pm2 || true
          pm2 restart dream-camper
