name: CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: connect to server and deploy changes
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASS }}
          port: 22
          script: |
            cd camper-client/
            git stash                            # Stash any local changes
            git pull origin master               # Pull the latest changes from the master branch
            git stash pop || echo "No stashed changes to apply"  # Attempt to reapply stashed changes if any

            rm -rf ./build
            rm -rf /var/www/dream-camper
            mkdir /var/www/dream-camper

            npm install --legacy-peer-deps       # Use --legacy-peer-deps to avoid dependency conflicts
            npm run build

            cp -rf ./build/* /var/www/dream-camper

            # Start the PM2 process if not running, otherwise restart it
            pm2 start npm --name "dream-camper" -- run start || pm2 restart dream-camper
